global using System;
global using System.Collections.Concurrent;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text;
global using System.Text.Json.Serialization;
global using System.Threading.Tasks;
global using MARS.Server.ApplicationState;
global using MARS.Server.Configuration;
global using MARS.Server.DataBaseContext;
global using MARS.Server.Exstensions;
global using MARS.Server.Hubs;
global using MARS.Server.Hubs.Interfaces;
global using MARS.Server.Services;
global using MARS.Server.Services.CommandExecutor.Entitys;
global using MARS.Server.Services.CommandExecutor.Entitys.Commands;
global using MARS.Server.Services.PyroAlerts.Entitys;
global using MARS.Server.Services.SoundRequest;
global using MARS.Server.Services.SoundRequest.Entities;
global using MARS.Server.Services.Telegram.BotService.Entitys;
global using MARS.Server.Services.Twitch.Entitys;
global using MARS.Server.Services.Twitch.Management;
global using MARS.Server.Services.Twitch.Rewards.ChannelRewards;
global using MARS.Server.Services.WaifuRoll.Entitys;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using Telegram.Bot;
global using Telegram.Bot.Types;
global using TwitchLib.Api.Helix.Models.ChannelPoints.CreateCustomReward;
global using TwitchLib.Api.Interfaces;
global using TwitchLib.Client.Events;
global using TwitchLib.Client.Interfaces;
global using TwitchLib.EventSub.Core.EventArgs.Channel;
global using TwitchLib.EventSub.Websockets;
global using Color = System.Drawing.Color;
global using Host = MARS.Server.Services.WaifuRoll.Entitys.Host;
global using Timer = System.Timers.Timer;
global using WTelegramClient = WTelegram.Client;
