// <auto-generated />
using System;
using MARS.Server.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250904142504_PgDumpSettings")]
    partial class PgDumpSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.Server.ApplicationState.RootState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("RandomMemeOnlineIsStop")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ApplicationState");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RandomMemeOnlineIsStop = false
                        });
                });

            modelBuilder.Entity("MARS.Server.Services.CinemaQueue.Entitys.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsNext")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitchUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CinemaQueue");
                });

            modelBuilder.Entity("MARS.Server.Services.DatabaseBackup.Models.PgDumpSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PgDumpPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PgDumpSettings");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Move", b =>
                {
                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("BlockFrame")
                        .HasColumnType("text");

                    b.Property<string>("CounterHitFrame")
                        .HasColumnType("text");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<bool>("HeatBurst")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatEngage")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatSmash")
                        .HasColumnType("boolean");

                    b.Property<string>("HitFrame")
                        .HasColumnType("text");

                    b.Property<string>("HitLevel")
                        .HasColumnType("text");

                    b.Property<bool>("Homing")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Notes")
                        .HasColumnType("text[]");

                    b.Property<bool>("PowerCrush")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresHeat")
                        .HasColumnType("boolean");

                    b.Property<string>("StanceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StanceName")
                        .HasColumnType("text");

                    b.Property<string>("StartUpFrame")
                        .HasColumnType("text");

                    b.Property<bool>("Throw")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tornado")
                        .HasColumnType("boolean");

                    b.HasKey("CharacterName", "Command");

                    b.ToTable("TekkenMoves");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Pending.MovePending", b =>
                {
                    b.Property<string>("CharacterName")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("text");

                    b.Property<string>("BlockFrame")
                        .HasColumnType("text");

                    b.Property<string>("CounterHitFrame")
                        .HasColumnType("text");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<bool>("HeatBurst")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatEngage")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeatSmash")
                        .HasColumnType("boolean");

                    b.Property<string>("HitFrame")
                        .HasColumnType("text");

                    b.Property<string>("HitLevel")
                        .HasColumnType("text");

                    b.Property<bool>("Homing")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Notes")
                        .HasColumnType("text[]");

                    b.Property<bool>("PowerCrush")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresHeat")
                        .HasColumnType("boolean");

                    b.Property<string>("StanceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StanceName")
                        .HasColumnType("text");

                    b.Property<string>("StartUpFrame")
                        .HasColumnType("text");

                    b.Property<bool>("Throw")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tornado")
                        .HasColumnType("boolean");

                    b.HasKey("CharacterName", "Command");

                    b.ToTable("TekkenMovesPending", (string)null);
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Pending.TekkenCharacterPending", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("AvatarImage")
                        .HasColumnType("bytea");

                    b.Property<string>("AvatarImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("FullBodyImage")
                        .HasColumnType("bytea");

                    b.Property<string>("FullBodyImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkToImage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("Strengths")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Weaknesess")
                        .HasColumnType("text[]");

                    b.HasKey("Name");

                    b.ToTable("TekkenCharactersPending", (string)null);
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.TekkenCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("AvatarImage")
                        .HasColumnType("bytea");

                    b.Property<string>("AvatarImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("FullBodyImage")
                        .HasColumnType("bytea");

                    b.Property<string>("FullBodyImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkToImage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("Strengths")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Weaknesess")
                        .HasColumnType("text[]");

                    b.HasKey("Name");

                    b.ToTable("TekkenCharacters");
                });

            modelBuilder.Entity("MARS.Server.Services.Honkai.Entitys.DailyAutoMarkupUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LTokenV2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastAutoMarkup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LtmidV2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LtuidV2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HonkaiMarkupUser");
                });

            modelBuilder.Entity("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("MARS.Server.Services.RandomMem.Entity.MemeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<int?>("MemeTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Order"));

                    b.HasKey("Id");

                    b.HasIndex("MemeTypeId");

                    b.ToTable("RandomMemeOrder");
                });

            modelBuilder.Entity("MARS.Server.Services.RandomMem.Entity.MemeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RandomMemeType");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FolderPath = "Alerts\\zvik",
                            Name = "Random Sound"
                        },
                        new
                        {
                            Id = 2,
                            FolderPath = "Alerts\\random_meme",
                            Name = "Random Meme"
                        });
                });

            modelBuilder.Entity("MARS.Server.Services.RandomMem.Entity.WTelegramAlloweedChannel", b =>
                {
                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.ToTable("WTelegramAlloweedChannels");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagSize")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderHeight")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderLeft")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderTop")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Padding")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarHeight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarWidth")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersLeft")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersRight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersTop")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreSize")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowFlags")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowSponsors")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowTags")
                        .HasColumnType("boolean");

                    b.Property<int>("Spacing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId")
                        .IsUnique();

                    b.ToTable("ScoreboardLayouts");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Final")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId", "Position")
                        .IsUnique();

                    b.ToTable("ScoreboardPlayers");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimationDuration")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FightModeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FightRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MainColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerNamesColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TournamentTitleColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ScoreboardStates");
                });

            modelBuilder.Entity("MARS.Server.Services.ServiceManager.Entitys.ServiceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsServiceActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceStates");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Authors")
                        .HasColumnType("text[]");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.PrimitiveCollection<string[]>("FeatAuthors")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Genre")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("LastTimePlays")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SoundRequestBaseTrackInfos");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.PlayerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("CurrentTrackDuration")
                        .HasColumnType("interval");

                    b.Property<Guid?>("CurrentTrackId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStoped")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NextTrackId")
                        .HasColumnType("uuid");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTrackId");

                    b.HasIndex("NextTrackId");

                    b.ToTable("SoundRequestPlayerState");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.SoundRequestBackgroundTrackId", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasIndex("TrackId")
                        .IsUnique();

                    b.ToTable("SoundRequestBackgroundTracks");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.UserRequestedTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestedTrackId")
                        .IsUnique();

                    b.ToTable("SoundRequestUserQueue");
                });

            modelBuilder.Entity("MARS.Server.Services.TelegramBotService.Entitys.TelegramUpdateReceiverOffset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelegramUpdateReceiverOffset");
                });

            modelBuilder.Entity("MARS.Server.Services.TelegramBotService.Entitys.TelegramUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ByeByeLastMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ByeByeServiceNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("GenshinImpactDailyNotif")
                        .HasColumnType("boolean");

                    b.Property<bool>("HonkaiNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRandomMemeSendler")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastTimeMessage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PyroAlertsAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("RaidHelper")
                        .HasColumnType("boolean");

                    b.Property<bool>("StreamUpNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ZenlessZoneZeroDailyNotif")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.ClientMessages.AutoMessages.Entitys.AutoMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutoMessages");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.FumoFriday.Entitys.FumoUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("FumoUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastTimeNotif")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MediaInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaInfoId")
                        .IsUnique();

                    b.ToTable("HelloVideosUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Management.Entitys.TokenInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ExpiresIn")
                        .HasColumnType("interval");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WhenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TwitchToken");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.MiniGamesStats.Entitys.TwitchLeaderboardUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RussianRouletteWins")
                        .HasColumnType("integer");

                    b.Property<int>("RussianRouletteWinsWithWaifu")
                        .HasColumnType("integer");

                    b.Property<int>("TekkenVictorinaWins")
                        .HasColumnType("integer");

                    b.Property<int>("TekkenVictorinaWinsWithWaifu")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWins")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWinsWithWaifus")
                        .HasColumnType("integer");

                    b.HasKey("TwitchId");

                    b.ToTable("TwitchLeaderboardUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Host", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("OrderCount")
                        .HasColumnType("bigint");

                    b.Property<string>("WaifuBrideId")
                        .HasColumnType("text");

                    b.Property<string>("WaifuRollId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WhenOrdered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WhenPrivated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("Hosts");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HostAutoHello", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HostId")
                        .IsUnique();

                    b.ToTable("AutoHello");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HostCoolDown", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HostId")
                        .IsUnique();

                    b.ToTable("CD");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Waifu", b =>
                {
                    b.Property<string>("ShikiId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Anime")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manga")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShikiId");

                    b.ToTable("Waifus");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.WaifuRollGuarantee", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRoll")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RollCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("WaifuRollGuarantees");
                });

            modelBuilder.Entity("MARS.Server.Services._365Genius.Entitys.Video365", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectLinkUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoHeight")
                        .HasColumnType("integer");

                    b.Property<int>("VideoWidth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Videos365");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Move", b =>
                {
                    b.HasOne("MARS.Server.Services.Framedata.Entitys.TekkenCharacter", "Character")
                        .WithMany("Movelist")
                        .HasForeignKey("CharacterName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Pending.MovePending", b =>
                {
                    b.HasOne("MARS.Server.Services.Framedata.Entitys.Pending.TekkenCharacterPending", "Character")
                        .WithMany("Movelist")
                        .HasForeignKey("CharacterName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", b =>
                {
                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaFileInfo", "FileInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Extension")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_Extension");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_FileName");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_LocalFilePath");

                            b1.Property<bool>("IsLocalFile")
                                .HasColumnType("boolean")
                                .HasColumnName("FileInfo_IsLocal");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_Type");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaMetaInfo", "MetaInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MetaInfo_DisplayName");

                            b1.Property<int>("Duration")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_Duration");

                            b1.Property<bool>("IsLooped")
                                .HasColumnType("boolean")
                                .HasColumnName("MetaInfo_IsLooped");

                            b1.Property<int>("Priority")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_Priority");

                            b1.Property<Guid?>("TwitchGuid")
                                .HasColumnType("uuid");

                            b1.Property<int>("TwitchPointsCost")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_TwitchPointsCost");

                            b1.Property<bool>("Vip")
                                .HasColumnType("boolean")
                                .HasColumnName("MetaInfo_VIP");

                            b1.Property<int>("Volume")
                                .HasColumnType("integer");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaPositionInfo", "PositionInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Height");

                            b1.Property<bool>("IsHorizontalCenter")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsHorizontalCenter");

                            b1.Property<bool>("IsProportion")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsProportion");

                            b1.Property<bool>("IsResizeRequires")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsResizeRequires");

                            b1.Property<bool>("IsRotated")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsRotated");

                            b1.Property<bool>("IsUseOriginalWidthAndHeight")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsVerticallCenter")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsVerticallCenter");

                            b1.Property<bool>("RandomCoordinates")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_RandomCoordinates");

                            b1.Property<int>("Rotation")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Rotation");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Width");

                            b1.Property<int>("XCoordinate")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_XCoordinate");

                            b1.Property<int>("YCoordinate")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_YCoordinate");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaStylesInfo", "StylesInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsBorder")
                                .HasColumnType("boolean")
                                .HasColumnName("StylesInfo_IsBorder");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaTextInfo", "TextInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<char?>("KeyWordSybmolDelimiter")
                                .HasColumnType("character(1)");

                            b1.Property<string>("KeyWordsColor")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_KeyWordsColor");

                            b1.Property<string>("Text")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_Text");

                            b1.Property<string>("TextColor")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_TextColor");

                            b1.Property<string>("TriggerWord")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_TriggerWord");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.Navigation("FileInfo")
                        .IsRequired();

                    b.Navigation("MetaInfo")
                        .IsRequired();

                    b.Navigation("PositionInfo")
                        .IsRequired();

                    b.Navigation("StylesInfo")
                        .IsRequired();

                    b.Navigation("TextInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("MARS.Server.Services.RandomMem.Entity.MemeOrder", b =>
                {
                    b.HasOne("MARS.Server.Services.RandomMem.Entity.MemeType", "Type")
                        .WithMany()
                        .HasForeignKey("MemeTypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", b =>
                {
                    b.HasOne("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", "ScoreboardState")
                        .WithOne("Layout")
                        .HasForeignKey("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", "ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardPlayer", b =>
                {
                    b.HasOne("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", "ScoreboardState")
                        .WithMany("Players")
                        .HasForeignKey("ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", b =>
                {
                    b.OwnsOne("MARS.Server.Services.SoundRequest.Entitys.YandexTrackAdditionalInfo", "YandexSpecificInfo", b1 =>
                        {
                            b1.Property<Guid>("BaseTrackInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ArtworkUrl")
                                .HasColumnType("text")
                                .HasColumnName("YandexInfo_ArtworkUrl");

                            b1.Property<string>("Mp3TrackUrl")
                                .HasColumnType("text")
                                .HasColumnName("YandexInfo_MP3Url");

                            b1.HasKey("BaseTrackInfoId");

                            b1.ToTable("SoundRequestBaseTrackInfos");

                            b1.WithOwner()
                                .HasForeignKey("BaseTrackInfoId");
                        });

                    b.Navigation("YandexSpecificInfo");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.PlayerState", b =>
                {
                    b.HasOne("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", "CurrentTrack")
                        .WithMany()
                        .HasForeignKey("CurrentTrackId");

                    b.HasOne("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", "NextTrack")
                        .WithMany()
                        .HasForeignKey("NextTrackId");

                    b.Navigation("CurrentTrack");

                    b.Navigation("NextTrack");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.SoundRequestBackgroundTrackId", b =>
                {
                    b.HasOne("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", "BaseTrackInfo")
                        .WithOne()
                        .HasForeignKey("MARS.Server.Services.SoundRequest.Entitys.SoundRequestBackgroundTrackId", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTrackInfo");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entitys.UserRequestedTrack", b =>
                {
                    b.HasOne("MARS.Server.Services.SoundRequest.Entitys.BaseTrackInfo", "RequestedTrack")
                        .WithOne()
                        .HasForeignKey("MARS.Server.Services.SoundRequest.Entitys.UserRequestedTrack", "RequestedTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedTrack");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", b =>
                {
                    b.HasOne("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", "MediaInfo")
                        .WithOne()
                        .HasForeignKey("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", "MediaInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaInfo");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HostAutoHello", b =>
                {
                    b.HasOne("MARS.Server.Services.WaifuRoll.Entitys.Host", "Host")
                        .WithOne("HostGreetings")
                        .HasForeignKey("MARS.Server.Services.WaifuRoll.Entitys.HostAutoHello", "HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HostCoolDown", b =>
                {
                    b.HasOne("MARS.Server.Services.WaifuRoll.Entitys.Host", "Host")
                        .WithOne("HostCoolDown")
                        .HasForeignKey("MARS.Server.Services.WaifuRoll.Entitys.HostCoolDown", "HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.Pending.TekkenCharacterPending", b =>
                {
                    b.Navigation("Movelist");
                });

            modelBuilder.Entity("MARS.Server.Services.Framedata.Entitys.TekkenCharacter", b =>
                {
                    b.Navigation("Movelist");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Host", b =>
                {
                    b.Navigation("HostCoolDown")
                        .IsRequired();

                    b.Navigation("HostGreetings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
