// <auto-generated />
using MARS.Server.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MARS.Server.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260522014400_add_paused_by_mute_to_player_state")]
partial class add_paused_by_mute_to_player_state
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Оставляем пустую модель: runtime использует сам Migration, а атрибут нужен для обнаружения миграции.
    }
}
