// <auto-generated />
using MARS.Server.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MARS.Server.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260519123000_RemoveNextQueueItemIdFromSoundRequest")]
partial class RemoveNextQueueItemIdFromSoundRequest
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Оставляем пустую модель: runtime использует сам Migration, а атрибут нужен для обнаружения миграции.
    }
}
