// <auto-generated />
using System;
using MARS.Server.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.Server.Migrations
{
    [DbContext(typeof(MigrationsDbContext))]
    [Migration("20260724193343_AddLastErrorToBinding")]
    partial class AddLastErrorToBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.Server.ApplicationState.RootState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RootState", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "RandomMemeOnlineIsStop",
                            Description = "Флаг остановки сервиса RandomMemeOnline",
                            TypeDescription = "bool",
                            Value = "False"
                        },
                        new
                        {
                            Name = "PuntoSwitcherFilterEnabled",
                            Description = "Флаг включения фильтра PuntoSwitcher",
                            TypeDescription = "bool",
                            Value = "True"
                        },
                        new
                        {
                            Name = "WaifuRollCooldownMinutes",
                            Description = "Кулдаун ролла вайфу в минутах",
                            TypeDescription = "long",
                            Value = "20"
                        },
                        new
                        {
                            Name = "WTelegramMtProxyUrl",
                            Description = "MTProxy URL для WTelegram (например: https://t.me/proxy?server=...)",
                            TypeDescription = "string",
                            Value = ""
                        },
                        new
                        {
                            Name = "WTelegramProxyUrl",
                            Description = "Прокси для WTelegram: socks5://user:pass@host:port или http://user:pass@host:port",
                            TypeDescription = "string",
                            Value = ""
                        });
                });

            modelBuilder.Entity("MARS.Server.Services.CinemaQueue.Entitys.CinemaMediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsNext")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("TwitchUserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId");

                    b.ToTable("CinemaQueue");
                });

            modelBuilder.Entity("MARS.Server.Services.DanbooruAutoPost.Entities.DanbooruAutoPostConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscordChannelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DanbooruAutoPostConfigs");
                });

            modelBuilder.Entity("MARS.Server.Services.EnvironmentVariable.Entitys.EnvironmentVariable", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagSize")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderHeight")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderLeft")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderTop")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Padding")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarHeight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarWidth")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersLeft")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersRight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersTop")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreSize")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowFlags")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowSponsors")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowTags")
                        .HasColumnType("boolean");

                    b.Property<int>("Spacing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId")
                        .IsUnique();

                    b.ToTable("ScoreboardLayouts");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Final")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId", "Position")
                        .IsUnique();

                    b.ToTable("ScoreboardPlayers");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimationDuration")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FightModeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FightRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MainColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerNamesColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TournamentTitleColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ScoreboardStates");
                });

            modelBuilder.Entity("MARS.Server.Services.ServiceManager.Entitys.ServiceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsServiceActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceStates");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entities.BaseTrackInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtworkUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Authors")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTimePlays")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("SoundRequestBaseTrackInfos");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entities.PlayerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentQueueItemId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("CurrentTrackProgress")
                        .HasColumnType("interval");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<bool>("PausedByMute")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("VideoState")
                        .HasColumnType("integer");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CurrentQueueItemId");

                    b.ToTable("SoundRequestPlayerState");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entities.QueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("QueueOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByTwitchId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueueOrder");

                    b.HasIndex("RequestedByTwitchId");

                    b.HasIndex("TrackId");

                    b.ToTable("SoundRequestQueueItems");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CheckSpan")
                        .HasColumnType("interval");

                    b.Property<int>("FileConvertType")
                        .HasColumnType("integer");

                    b.Property<string>("FileNameFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConvertFile")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TelegramChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("StreamArchiveConfigs");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunksCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProcessedFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId", "OriginalFilePath")
                        .IsUnique();

                    b.ToTable("StreamArchiveFiles");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFileChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("integer");

                    b.Property<long>("ChunkSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<long>("OffsetInOriginalFile")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("StreamArchiveFileChunks");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.BotService.Entitys.TelegramUpdateReceiverOffset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelegramUpdateReceiverOffset");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.BotService.Entitys.TelegramUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ByeByeLastMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ByeByeServiceNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("GenshinImpactDailyNotif")
                        .HasColumnType("boolean");

                    b.Property<bool>("HonkaiNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRandomMemeSendler")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTimeMessage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PyroAlertsAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("RaidHelper")
                        .HasColumnType("boolean");

                    b.Property<bool>("StreamUpNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ZenlessZoneZeroDailyNotif")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.DiscordBridge.Entities.TelegramDiscordChannelBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordChannelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TelegramChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChannelId", "DiscordChannelId")
                        .IsUnique();

                    b.ToTable("TelegramDiscordChannelBindings");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.DiscordBridge.Entities.TelegramDiscordChannelState", b =>
                {
                    b.Property<long>("TelegramChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramChannelId"));

                    b.Property<int>("LastProcessedMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TelegramChannelId");

                    b.ToTable("TelegramDiscordChannelStates");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.PrivateChannelsResender.Entities.ChannelProcessingState", b =>
                {
                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChannelId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MessagesHash")
                        .HasColumnType("bigint");

                    b.Property<int>("OffsetId")
                        .HasColumnType("integer");

                    b.HasKey("ChannelId");

                    b.ToTable("ChannelProcessingStates");
                });

            modelBuilder.Entity("MARS.Server.Services.Telegram.WTelegram.Entities.WTelegramSession", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Name");

                    b.ToTable("WTelegramSessions");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.ClientMessages.AutoMessages.Entitys.AutoMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutoMessages");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.Frog", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pid"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Habits")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("RussianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Pid");

                    b.ToTable("Frogs");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.Fumo", b =>
                {
                    b.Property<int>("MfcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MfcId"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CharacterTranslit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WhenAdded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MfcId");

                    b.ToTable("Fumos");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.MikuModule", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Designer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JapaneseName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Songs")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PageId");

                    b.ToTable("MikuModules");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.MikuMondayActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MikuMondayTrackId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MikuMondayTrackId");

                    b.HasIndex("TwitchUserId", "Year", "WeekOfYear")
                        .IsUnique();

                    b.ToTable("MikuMondayActivations");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.MikuMondayTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BaseTrackInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseTrackInfoId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("MikuMondayTracks");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.RollCooldown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastRollTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId", "RollType")
                        .IsUnique();

                    b.ToTable("RollCooldowns");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.TwitchUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TwitchId");

                    b.Property<string>("AliasNickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChatColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FollowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInBlockList")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TwitchId");

                    b.ToTable("TwitchUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.UserFumoCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FumoMfcId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId", "FumoMfcId")
                        .IsUnique();

                    b.ToTable("UserFumoCollections");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.UserMikuCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MikuPageId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId", "MikuPageId")
                        .IsUnique();

                    b.ToTable("UserMikuCollections");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastTimeNotif")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MediaInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MediaInfoId")
                        .IsUnique();

                    b.HasIndex("TwitchId");

                    b.ToTable("HelloVideosUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Management.Entitys.TokenInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ExpiresIn")
                        .HasColumnType("interval");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TwitchToken");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.MiniGamesStats.Entitys.TwitchLeaderboardUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RussianRouletteWins")
                        .HasColumnType("integer");

                    b.Property<int>("RussianRouletteWinsWithWaifu")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWins")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWinsWithWaifus")
                        .HasColumnType("integer");

                    b.HasKey("TwitchId");

                    b.ToTable("TwitchLeaderboardUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards.ChannelRewards.Entities.ChannelRewardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalCooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobalCooldownEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaxPerStreamEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaxPerUserPerStreamEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserInputRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPerStream")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPerUserPerStream")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<bool>("ShouldRedemptionsSkipRequestQueue")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchRewardId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChannelRewards");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._11_RandomMemReward.Service.Entity.MemeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<bool>("IsFileNotConvertable")
                        .HasColumnType("boolean");

                    b.Property<int?>("MemeTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Order"));

                    b.HasKey("Id");

                    b.HasIndex("MemeTypeId");

                    b.ToTable("RandomMemeOrder");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._11_RandomMemReward.Service.Entity.MemeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RandomMemeType");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FolderPath = "Alerts\\zvik",
                            Name = "Random Sound"
                        },
                        new
                        {
                            Id = 2,
                            FolderPath = "Alerts\\random_meme",
                            Name = "Random Meme"
                        });
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._11_RandomMemReward.Service.Entity.WTelegramAlloweedChannel", b =>
                {
                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.ToTable("WTelegramAlloweedChannels");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._13_FumoFriday.Entitys.FumoUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("FumoUsers");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Synthesizer.Entitys.SevenTvEmote", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("SevenTvEmotes");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.TwitchFollowers.Entitys.FollowerInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("FollowersEntitys");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.AutoHelloMessage", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Guid");

                    b.ToTable("AutoHelloMessages");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Husband", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastWeddingCongratulatedMonths")
                        .HasColumnType("integer");

                    b.Property<long>("OrderCount")
                        .HasColumnType("bigint");

                    b.Property<string>("WaifuBrideId")
                        .HasColumnType("text");

                    b.Property<string>("WaifuRollId")
                        .HasColumnType("text");

                    b.Property<DateTime>("WhenOrdered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WhenPrivated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("Husbands");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HusbandAutoHello", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HusbandId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HusbandId")
                        .IsUnique();

                    b.ToTable("HusbandAutoHelloCooldowns");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HusbandCoolDown", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HusbandId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HusbandId")
                        .IsUnique();

                    b.ToTable("HusbandCoolDowns");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Waifu", b =>
                {
                    b.Property<string>("ShikiId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Anime")
                        .HasColumnType("text");

                    b.Property<Guid?>("AudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manga")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShikiId");

                    b.HasIndex("AudioId");

                    b.ToTable("Waifus");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.WaifuRollAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AudioData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WaifuRollAudios");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.WaifuRollGuarantee", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRoll")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RollCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("WaifuRollGuarantees");
                });

            modelBuilder.Entity("MARS.Server.Services._365Genius.Entitys.Video365", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectLinkUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<long>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoHeight")
                        .HasColumnType("integer");

                    b.Property<int>("VideoWidth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Videos365");
                });

            modelBuilder.Entity("MARS.Server.Services.CinemaQueue.Entitys.CinemaMediaItem", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", b =>
                {
                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaFileInfo", "FileInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Extension")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_Extension");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_FileName");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_LocalFilePath");

                            b1.Property<bool>("IsFileNotConvertable")
                                .HasColumnType("boolean")
                                .HasColumnName("FileInfo_IsFileNotConvertable");

                            b1.Property<bool>("IsLocalFile")
                                .HasColumnType("boolean")
                                .HasColumnName("FileInfo_IsLocal");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FileInfo_Type");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaMetaInfo", "MetaInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MetaInfo_DisplayName");

                            b1.Property<int>("Duration")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_Duration");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsFreezeRequired")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsLooped")
                                .HasColumnType("boolean")
                                .HasColumnName("MetaInfo_IsLooped");

                            b1.Property<int>("Priority")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_Priority");

                            b1.Property<Guid?>("TwitchGuid")
                                .HasColumnType("uuid");

                            b1.Property<int>("TwitchPointsCost")
                                .HasColumnType("integer")
                                .HasColumnName("MetaInfo_TwitchPointsCost");

                            b1.Property<bool>("Vip")
                                .HasColumnType("boolean")
                                .HasColumnName("MetaInfo_VIP");

                            b1.Property<int>("Volume")
                                .HasColumnType("integer");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaPositionInfo", "PositionInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Height");

                            b1.Property<bool>("IsHorizontalCenter")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsHorizontalCenter");

                            b1.Property<bool>("IsProportion")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsProportion");

                            b1.Property<bool>("IsResizeRequires")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsResizeRequires");

                            b1.Property<bool>("IsRotated")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsRotated");

                            b1.Property<bool>("IsUseOriginalWidthAndHeight")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsVerticallCenter")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_IsVerticallCenter");

                            b1.Property<bool>("RandomCoordinates")
                                .HasColumnType("boolean")
                                .HasColumnName("PositionInfo_RandomCoordinates");

                            b1.Property<int>("Rotation")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Rotation");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_Width");

                            b1.Property<int>("XCoordinate")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_XCoordinate");

                            b1.Property<int>("YCoordinate")
                                .HasColumnType("integer")
                                .HasColumnName("PositionInfo_YCoordinate");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaStylesInfo", "StylesInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsBorder")
                                .HasColumnType("boolean")
                                .HasColumnName("StylesInfo_IsBorder");

                            b1.Property<bool>("IsShowLetterbox")
                                .HasColumnType("boolean")
                                .HasColumnName("StylesInfo_IsShowLetterbox");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.OwnsOne("MARS.Server.Services.PyroAlerts.Entitys.MediaTextInfo", "TextInfo", b1 =>
                        {
                            b1.Property<Guid>("MediaInfoId")
                                .HasColumnType("uuid");

                            b1.Property<char?>("KeyWordSybmolDelimiter")
                                .HasColumnType("character(1)");

                            b1.Property<string>("KeyWordsColor")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_KeyWordsColor");

                            b1.Property<string>("Text")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_Text");

                            b1.Property<string>("TextColor")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_TextColor");

                            b1.Property<string>("TriggerWord")
                                .HasColumnType("text")
                                .HasColumnName("TextInfo_TriggerWord");

                            b1.HasKey("MediaInfoId");

                            b1.ToTable("Alerts");

                            b1.WithOwner()
                                .HasForeignKey("MediaInfoId");
                        });

                    b.Navigation("FileInfo")
                        .IsRequired();

                    b.Navigation("MetaInfo")
                        .IsRequired();

                    b.Navigation("PositionInfo")
                        .IsRequired();

                    b.Navigation("StylesInfo")
                        .IsRequired();

                    b.Navigation("TextInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", b =>
                {
                    b.HasOne("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", "ScoreboardState")
                        .WithOne("Layout")
                        .HasForeignKey("MARS.Server.Services.Scoreboard.Entitys.ScoreboardLayout", "ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardPlayer", b =>
                {
                    b.HasOne("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", "ScoreboardState")
                        .WithMany("Players")
                        .HasForeignKey("ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entities.PlayerState", b =>
                {
                    b.HasOne("MARS.Server.Services.SoundRequest.Entities.QueueItem", "CurrentQueueItem")
                        .WithMany()
                        .HasForeignKey("CurrentQueueItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentQueueItem");
                });

            modelBuilder.Entity("MARS.Server.Services.SoundRequest.Entities.QueueItem", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "RequestedByTwitchUser")
                        .WithMany()
                        .HasForeignKey("RequestedByTwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MARS.Server.Services.SoundRequest.Entities.BaseTrackInfo", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedByTwitchUser");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFile", b =>
                {
                    b.HasOne("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveConfig", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFileChunk", b =>
                {
                    b.HasOne("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFile", "File")
                        .WithMany("Chunks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.MikuMondayActivation", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.MikuMondayTrack", "MikuMondayTrack")
                        .WithMany()
                        .HasForeignKey("MikuMondayTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MikuMondayTrack");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Entitys.MikuMondayTrack", b =>
                {
                    b.HasOne("MARS.Server.Services.SoundRequest.Entities.BaseTrackInfo", "BaseTrackInfo")
                        .WithMany()
                        .HasForeignKey("BaseTrackInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseTrackInfo");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", b =>
                {
                    b.HasOne("MARS.Server.Services.PyroAlerts.Entitys.MediaInfo", "MediaInfo")
                        .WithOne()
                        .HasForeignKey("MARS.Server.Services.Twitch.HelloVideos.Entitys.HelloVideosUsers", "MediaInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaInfo");

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.MiniGamesStats.Entitys.TwitchLeaderboardUser", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._11_RandomMemReward.Service.Entity.MemeOrder", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Rewards._11_RandomMemReward.Service.Entity.MemeType", "Type")
                        .WithMany()
                        .HasForeignKey("MemeTypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.Rewards._13_FumoFriday.Entitys.FumoUser", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.Twitch.TwitchFollowers.Entitys.FollowerInfo", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithOne()
                        .HasForeignKey("MARS.Server.Services.Twitch.TwitchFollowers.Entitys.FollowerInfo", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Husband", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HusbandAutoHello", b =>
                {
                    b.HasOne("MARS.Server.Services.WaifuRoll.Entitys.Husband", "Husband")
                        .WithOne("HusbandGreetings")
                        .HasForeignKey("MARS.Server.Services.WaifuRoll.Entitys.HusbandAutoHello", "HusbandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Husband");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.HusbandCoolDown", b =>
                {
                    b.HasOne("MARS.Server.Services.WaifuRoll.Entitys.Husband", "Husband")
                        .WithOne("HusbandCoolDown")
                        .HasForeignKey("MARS.Server.Services.WaifuRoll.Entitys.HusbandCoolDown", "HusbandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Husband");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Waifu", b =>
                {
                    b.HasOne("MARS.Server.Services.WaifuRoll.Entitys.WaifuRollAudio", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId");

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.WaifuRollGuarantee", b =>
                {
                    b.HasOne("MARS.Server.Services.Twitch.Entitys.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.Server.Services.Scoreboard.Entitys.ScoreboardState", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("MARS.Server.Services.StreamAcrhive_UNUSED.Entitys.StreamArchiveFile", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("MARS.Server.Services.WaifuRoll.Entitys.Husband", b =>
                {
                    b.Navigation("HusbandCoolDown");

                    b.Navigation("HusbandGreetings");
                });
#pragma warning restore 612, 618
        }
    }
}
